language: java

jdk:
  - oraclejdk11
  - openjdk11

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle



# Specify a display with xvfb for UI testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

